<?php

chdir(__DIR__ . '/../../');
require_once './BreakpointDebugging_Including.php';

use \BreakpointDebugging as B;

function test__construct()
{
    $previous = new \Exception('Previous message.');
    new \BreakpointDebugging_Exception('Test message.', 1, $previous, 0);
    new \BreakpointDebugging_Exception('Test message.', 1, $previous);
    new \BreakpointDebugging_Exception('Test message.', 1);
    new \BreakpointDebugging_Exception('Test message.');
}

//B::isUnitTestExeMode('UNIT_TEST');
B::isUnitTestExeMode(true);

if (B::getStatic('$exeMode') & B::RELEASE) { // In case of release.
    class BreakpointDebugging_ExceptionTest extends \BreakpointDebugging_UnitTestOverriding
    {
        /**
         * @covers \BreakpointDebugging_Exception<extended>
         */
        public function test__construct()
        {
            test__construct();
        }

    }

} else { // In case of debug.
    /**
     * Test class for BreakpointDebugging_Exception.
     * Generated by PHPUnit on 2012-09-30 at 16:24:28.
     */
    class BreakpointDebugging_ExceptionTest extends \BreakpointDebugging_UnitTestOverriding
    {
        /**
         * @covers \BreakpointDebugging_Exception<extended>
         */
        public function test__construct()
        {
            test__construct();
        }

        /**
         * @covers \BreakpointDebugging_Exception<extended>
         *
         * @expectedException        \BreakpointDebugging_ErrorException
         * @expectedExceptionMessage CLASS=BreakpointDebugging_Exception FUNCTION=__construct ID=1
         */
        public function test__construct_B()
        {
            new \BreakpointDebugging_Exception('dummy', 'dummy', 'dummy', 'dummy', 'dummy');
        }

        /**
         * @covers \BreakpointDebugging_Exception<extended>
         *
         * @expectedException        \BreakpointDebugging_ErrorException
         * @expectedExceptionMessage CLASS=BreakpointDebugging_Exception FUNCTION=__construct ID=2
         */
        public function test__construct_C()
        {
            new \BreakpointDebugging_Exception(1);
        }

        /**
         * @covers \BreakpointDebugging_Exception<extended>
         *
         * @expectedException        \BreakpointDebugging_ErrorException
         * @expectedExceptionMessage CLASS=BreakpointDebugging_Exception FUNCTION=__construct ID=3
         */
        public function test__construct_D()
        {
            new \BreakpointDebugging_Exception('OK', 'Error');
        }

        /**
         * @covers \BreakpointDebugging_Exception<extended>
         *
         * @expectedException        \BreakpointDebugging_ErrorException
         * @expectedExceptionMessage CLASS=BreakpointDebugging_Exception FUNCTION=__construct ID=7
         */
        public function test__construct_E()
        {
            new \BreakpointDebugging_Exception('OK', 1, null, 'Error');
        }

        /**
         * @covers \BreakpointDebugging_Exception<extended>
         *
         * @expectedException        \BreakpointDebugging_ErrorException
         * @expectedExceptionMessage CLASS=BreakpointDebugging_Exception FUNCTION=__construct ID=7
         */
        public function test__construct_F()
        {
            new \BreakpointDebugging_Exception('OK', 1, null, -1);
        }

        /**
         * @covers \BreakpointDebugging_Exception<extended>
         *
         * @expectedException        \BreakpointDebugging_ErrorException
         * @expectedExceptionMessage CLASS=BreakpointDebugging_Exception FUNCTION=__construct ID=5
         */
        public function test__construct_G()
        {
            new \BreakpointDebugging_Exception('OK', 1, 'Error', 1);
        }

        /**
         * @covers \BreakpointDebugging_Exception<extended>
         *
         * @expectedException        \BreakpointDebugging_ErrorException
         * @expectedExceptionMessage CLASS=BreakpointDebugging_Exception FUNCTION=__construct ID=6
         */
        public function test__construct_H()
        {
            $previous = new \Exception('Previous message.');
            // SJIS message.
            new \BreakpointDebugging_Exception("\x95\xB6\x8E\x9A", 1, $previous, 1);
        }

    }

}

?>
