<?php

chdir(__DIR__ . '/../../');
require_once './PEAR_Setting/BreakpointDebugging_MySetting.php';

use \BreakpointDebugging as B;

B::checkUnitTestExeMode();

/**
 * Test class for BreakpointDebugging_Exception.
 * Generated by PHPUnit on 2012-09-30 at 16:24:28.
 */
class BreakpointDebugging_ExceptionTest extends \BreakpointDebugging_UnitTest
{
    /**
     * Tests exception throwing.
     */
    public function testSometing()
    {
        while (true) {
            try {
                throw new \BreakpointDebugging_Exception('Test message.');
            } catch (\BreakpointDebugging_Exception $e) {
                $this->assertTrue($e->getMessage() === 'Test message.');
                break;
            }
            $this->assertTrue(false);
        }

        while (true) {
            try {
                throw new \BreakpointDebugging_Exception('Test message.', 123);
            } catch (\BreakpointDebugging_Exception $e) {
                $this->assertTrue($e->getMessage() === 'Test message.');
                $this->assertTrue($e->getCode() === 123);
                break;
            }
            $this->assertTrue(false);
        }

        while (true) {
            try {
                $previous = new \Exception('Previous message.');
                throw new \BreakpointDebugging_Exception('Test message.', 123, $previous);
            } catch (\BreakpointDebugging_Exception $e) {
                $this->assertTrue($e->getMessage() === 'Test message.');
                $this->assertTrue($e->getCode() === 123);
                $this->assertTrue($e->getCause() === $previous);
                break;
            }
            $this->assertTrue(false);
        }
    }

}

?>
