<?php

chdir(__DIR__ . '/../../');
require_once './PEAR_Setting/BreakpointDebugging_MySetting.php';

use \BreakpointDebugging as B;

B::checkUnitTestExeMode();

$testAutoload = 1;
if ($testAutoload === 1) { // The case which extends base class.

    class AutoloadTest extends \NativeClass
    {

    }

}

/**
 * Test class for BreakpointDebugging_InAllCase.
 * Generated by PHPUnit on 2012-09-30 at 16:24:30.
 */
class BreakpointDebugging_InAllCaseTest extends PHPUnit_Framework_TestCase
{
    const TEST_CONST = 'The test constant.';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers BreakpointDebugging_InAllCase::registerNotFixedLocation
     */
    public function testRegisterNotFixedLocation()
    {
        global $_BreakpointDebugging;
        static $isRegister;

        B::registerNotFixedLocation($isRegister);
        $notFixedLocation = $_BreakpointDebugging->notFixedLocations[count($_BreakpointDebugging->notFixedLocations) - 1];
        $this->assertTrue($notFixedLocation['function'] === 'testRegisterNotFixedLocation');
        $this->assertTrue($notFixedLocation['class'] === 'BreakpointDebugging_InAllCaseTest');
        $this->assertTrue(!array_key_exists('file', $notFixedLocation));
    }

    /**
     * @covers BreakpointDebugging_InAllCase::addValuesToTrace
     */
    public function testAddValuesToTrace()
    {
        global $_BreakpointDebugging;

        $testString = 'The test character string.';
        $values = array ('TEST_CONST' => BreakpointDebugging_InAllCaseTest::TEST_CONST, '$testString' => $testString);
        B::addValuesToTrace($values);
        $line = __LINE__ - 1;
        $valuesToTrace = $_BreakpointDebugging->valuesToTrace[__FILE__][$line];
        $this->assertTrue($valuesToTrace['function'] === 'testAddValuesToTrace');
        $this->assertTrue($valuesToTrace['class'] === 'BreakpointDebugging_InAllCaseTest');
        $this->assertTrue(!array_key_exists('file', $valuesToTrace));
        $this->assertTrue($valuesToTrace['values'] === $values);
    }

    /**
     * @covers BreakpointDebugging_InAllCase::convertMbString
     */
    public function testConvertMbString()
    {
        while (true) {
            try {
                // SJIS
                B::convertMbString("\x95\xB6\x8E\x9A ");
            } catch (\Exception $e) {
                $this->assertTrue(false);
            }
            break;
        }
        B::setPropertyForTest('\BreakpointDebugging_InAllCase', '$_onceErrorDispFlag', false);

        while (true) {
            try {
                // UTF-8
                B::convertMbString("\xE6\x96\x87\xE5\xAD\x97 ");
            } catch (\Exception $e) {
                $this->assertTrue(false);
            }
            break;
        }
        B::setPropertyForTest('\BreakpointDebugging_InAllCase', '$_onceErrorDispFlag', false);

        while (true) {
            try {
                // SJIS + UTF-8
                B::convertMbString("\x95\xB6\x8E\x9A \xE6\x96\x87\xE5\xAD\x97 ");
            } catch (\BreakpointDebugging_Error_Exception $e) {
                break;
            }
            $this->assertTrue(false);
            break;
        }
        B::setPropertyForTest('\BreakpointDebugging_InAllCase', '$_onceErrorDispFlag', false);
    }

    /**
     * @covers BreakpointDebugging_InAllCase::mkdir
     */
    public function testMkdir()
    {
        $testDirName = B::$workDir . '/TestMkDir';
        if (is_dir($testDirName)) {
            rmdir($testDirName);
        }
        B::mkdir($testDirName, 0700);
        $this->assertTrue(is_dir($testDirName));
        if (B::$os === 'WIN') {
            return;
        }
        clearstatcache();
        $this->assertTrue(fileperms($testDirName) === 0700);
    }

    /**
     * @covers BreakpointDebugging_InAllCase::fopen
     */
    public function testFopen()
    {
        $testFileName = B::$workDir . '/TestFopen.txt';
        if (is_file($testFileName)) {
            unlink($testFileName);
        }
        $pFile = B::fopen($testFileName, 'w+b', 0700);
        fclose($pFile);
        $this->assertTrue(is_file($testFileName));
        if (B::$os === 'WIN') {
            return;
        }
        clearstatcache();
        $this->assertTrue(fileperms($testFileName) === 0700);
    }

    /**
     * @covers BreakpointDebugging_InAllCase::compressIntArray
     * @covers BreakpointDebugging_InAllCase::decompressIntArray
     */
    public function testCompressThenDecompressIntArray()
    {
        $intArray = array ();
        for ($count = 0; $count <= 400; $count++) {
            $intArray[] = $count;
        }
        $pFile = fopen(B::$workDir . 'test.bin', 'w+b');
        fwrite($pFile, B::compressIntArray($intArray));
        fwrite($pFile, B::compressIntArray($intArray));
        fflush($pFile);
        rewind($pFile);
        while ($intResultArray = B::decompressIntArray(fgets($pFile))) {
            $this->assertTrue($intArray === $intResultArray);
        }
        fclose($pFile);
    }

    /**
     * @covers BreakpointDebugging_InAllCase::autoload
     */
    public function testAutoload()
    {
        global $testAutoload;

        if ($testAutoload === 2) { // In case of accessing to static member.
            ob_start();
            \NativeClass::publicStaticFunction();
            ob_end_clean();
        }

        if ($testAutoload === 3) { // In case of creating new instance.
            new \NativeClass();
        }
    }

    /**
     * @covers BreakpointDebugging_InAllCase::exceptionHandler
     */
    public function testExceptionHandler()
    {
        try {
            $pPrevious = new \Exception('Previous exception.', E_USER_ERROR);
            $pException = new \Exception('Exception.', E_USER_ERROR, $pPrevious);
            B::exceptionHandler($pException);
        } catch (\BreakpointDebugging_UnitTest_Exception $e) {
            return;
        }
        $this->assertTrue(false);
    }

    /**
     * @covers BreakpointDebugging_InAllCase::errorHandler
     */
    public function testErrorHandler()
    {
        try {
            B::errorHandler(E_USER_ERROR, 'Error test.');
        } catch (\BreakpointDebugging_UnitTest_Exception $e) {
            return;
        }
        $this->assertTrue(false);
    }

    /**
     * @covers BreakpointDebugging_InAllCase::internalAssert
     */
    public function testInternalAssert()
    {
        while (true) {
            try {
                B::internalAssert(false);
            } catch (\BreakpointDebugging_UnitTest_Exception $e) {
                break;
            }
            $this->assertTrue(false);
            break;
        }
        B::setPropertyForTest('\BreakpointDebugging_InAllCase', '$_onceErrorDispFlag', false);
    }

    /**
     * @covers BreakpointDebugging_InAllCase::internalException
     */
    public function testInternalException()
    {
        while (true) {
            try {
                B::internalException('Tests "internalException()".');
            } catch (\BreakpointDebugging_UnitTest_Exception $e) {
                break;
            }
            $this->assertTrue(false);
            break;
        }
        B::setPropertyForTest('\BreakpointDebugging_InAllCase', '$_onceErrorDispFlag', false);
    }

    /**
     * @covers BreakpointDebugging_InAllCase::shutdown
     */
    public function testShutdown()
    {
        global $_BreakpointDebugging, $_BreakpointDebugging_InAllCaseTest_ForDebug;

        $_BreakpointDebugging_InAllCaseTest_ForDebug = new \BreakpointDebugging_InAllCaseTest_ForDebug();
        try {
            // Emulates this page shutdown.
            \BreakpointDebugging_InAllCase::shutdown();
        } catch (\BreakpointDebugging_UnitTest_Exception $e) {
            $this->assertTrue(!is_object($_BreakpointDebugging_InAllCaseTest_ForDebug));
            $this->assertTrue(is_object($_BreakpointDebugging));
            return;
        }
        $this->assertTrue(false);
    }

}

class BreakpointDebugging_InAllCaseTest_ForDebug
{
    function __destruct()
    {
        // Throws "\BreakpointDebugging_UnitTest_Exception" inside "__destruct()" class method.
        assert(false);
    }

}

?>
