<?php

chdir(__DIR__ . '/../../../');
require_once './PEAR_Setting/BreakpointDebugging_MySetting.php';

use \BreakpointDebugging as B;

B::checkUnitTestExeMode();

/**
 * Test class for BreakpointDebugging_Error.
 * Generated by PHPUnit on 2012-10-08 at 13:08:45.
 */
class BreakpointDebugging_ErrorTest extends PHPUnit_Framework_TestCase
{
    static $error;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    function setUp()
    {
        $errorLogDirectory = B::$workDir . '/ErrorLog/';
        if (!is_dir($errorLogDirectory)) {
            return;
        }
        $errorLogDirElements = scandir($errorLogDirectory);
        foreach ($errorLogDirElements as $errorLogDirElement) {
            $errorLogDirElementPath = $errorLogDirectory . $errorLogDirElement;
            if (!is_file($errorLogDirElementPath)) {
                continue;
            }
            // Deletes the error log file, variable configuring file or the error location file.
            unlink($errorLogDirElementPath);
        }
    }

    /**
     * @covers BreakpointDebugging_Error::exceptionHandler2
     */
    public function testExceptionHandler2()
    {
        global $line1_, $line2_, $lineA_, $lineB_;

        B::setPropertyForTest('BreakpointDebugging_InAllCase', '$_handlerOf', 'exception'); // This registers as exception handler.
        self::$error = new \BreakpointDebugging_Error();

        require_once __DIR__ . '/testExceptionHandler2_Parent.php';
        $lineParent = __LINE__ - 1;
        function test2_()
        {
            global $line1_;

            BreakpointDebugging_ErrorTest::$error->exceptionHandler2(new \Exception(), B::$prependExceptionLog);
            $line1_ = __LINE__ - 1;
        }

        function test1_()
        {
            global $line2_;

            test2_();
            $line2_ = __LINE__ - 1;
        }

        BreakpointDebugging_ErrorTest::$error->exceptionHandler2(new \Exception(), B::$prependExceptionLog);
        $line = __LINE__ - 1;
        test1_();
        $line3 = __LINE__ - 1;

        $binData1 = file_get_contents(B::$workDir . '/ErrorLog/1.bin');

        $cmpBinData1 = rtrim(B::compressIntArray(array (1, $line__, 2, $lineParent)), PHP_EOL);
        $this->assertTrue(strpos($binData1, $cmpBinData1) !== false);

        $cmpBinData1 = rtrim(B::compressIntArray(array (1, $lineA_, 1, $lineB_, 1, $lineC_, 2, $lineParent)), PHP_EOL);
        $this->assertTrue(strpos($binData1, $cmpBinData1) !== false);

        $binData2 = file_get_contents(B::$workDir . '/ErrorLog/2.bin');

        $cmpBinData2 = rtrim(B::compressIntArray(array (2, $line)), PHP_EOL);
        $this->assertTrue(strpos($binData2, $cmpBinData2) !== false);

        $cmpBinData2 = rtrim(B::compressIntArray(array (2, $line1_, 2, $line2_, 2, $line3)), PHP_EOL);
        $this->assertTrue(strpos($binData2, $cmpBinData2) !== false);

        B::setPropertyForTest('BreakpointDebugging_InAllCase', '$_handlerOf', 'none'); // This registers as none handler.
    }

    /**
     * @covers BreakpointDebugging_Error::errorHandler2
     */
    public function testErrorHandler2()
    {
        global $line1, $line2, $lineA, $lineB;

        $handlerStore = B::getPropertyForTest('BreakpointDebugging_InAllCase', '$_handlerOf'); // Stores the handler.
        B::setPropertyForTest('BreakpointDebugging_InAllCase', '$_handlerOf', 'error'); // This registers as error handler.
        self::$error = new \BreakpointDebugging_Error();
        function errorHandler()
        {
            BreakpointDebugging_ErrorTest::$error->errorHandler2(E_USER_ERROR, '', B::$prependErrorLog);
        }

        function trigger_error2()
        {
            errorHandler();
        }

        require_once __DIR__ . '/testErrorHandler2_Parent.php';
        $lineParent = __LINE__ - 1;
        function test2()
        {
            global $line1;

            trigger_error2();
            $line1 = __LINE__ - 1;
        }

        function test1()
        {
            global $line2;

            test2();
            $line2 = __LINE__ - 1;
        }

        trigger_error2();
        $line = __LINE__ - 1;
        test1();
        $line3 = __LINE__ - 1;

        $binData1 = file_get_contents(B::$workDir . '/ErrorLog/1.bin');

        $cmpBinData1 = rtrim(B::compressIntArray(array (1, $line_, 2, $lineParent)), PHP_EOL);
        $this->assertTrue(strpos($binData1, $cmpBinData1) !== false);

        $cmpBinData1 = rtrim(B::compressIntArray(array (1, $lineA, 1, $lineB, 1, $lineC, 2, $lineParent)), PHP_EOL);
        $this->assertTrue(strpos($binData1, $cmpBinData1) !== false);

        $binData2 = file_get_contents(B::$workDir . '/ErrorLog/2.bin');

        $cmpBinData2 = rtrim(B::compressIntArray(array (2, $line)), PHP_EOL);
        $this->assertTrue(strpos($binData2, $cmpBinData2) !== false);

        $cmpBinData2 = rtrim(B::compressIntArray(array (2, $line1, 2, $line2, 2, $line3)), PHP_EOL);
        $this->assertTrue(strpos($binData2, $cmpBinData2) !== false);

        B::setPropertyForTest('BreakpointDebugging_InAllCase', '$_handlerOf', $handlerStore); // Restores handler.
    }

}

?>
