<?php

//require_once dirname(__FILE__) . '/../../../LockByShmop.php';
chdir('../../../../../');
require_once './PEAR_Setting/BreakpointDebugging_MySetting.php';

/**
 * Test class for BreakpointDebugging_LockByShmop.
 * Generated by PHPUnit on 2012-05-25 at 15:10:24.
 */
class BreakpointDebugging_LockByShmopTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var BreakpointDebugging_LockByShmop
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BreakpointDebugging_LockByShmop;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers BreakpointDebugging_LockByShmop::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
        'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BreakpointDebugging_LockByShmop::lock
     * @todo Implement testLock().
     */
    public function testLock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
        'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BreakpointDebugging_LockByShmop::unlock
     * @todo Implement testUnlock().
     */
    public function testUnlock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
        'This test has not been implemented yet.'
        );
    }

}

?>
